### ISSUE TITLE
panic: http: multiple registrations for /debug/requests

### ISSUE THREAD

**Issue by miyabyte** [go-kratos/etcd#2]
go.etcd.io/etcd v2.3.8+incompatible
github.com/coreos/etcd/ v2.3.8+incompatible
这两个同时具有↓
func init() {
	http.HandleFunc("/debug/requests", fun

导致：
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x1bf34a0, 0x175e756, 0xf, 0x18178a0, 0x1786d68)
        /usr/local/go/src/net/http/server.go:2433 +0x2c5
net/http.(*ServeMux).HandleFunc(...)
        /usr/local/go/src/net/http/server.go:2470
net/http.HandleFunc(...)
        /usr/local/go/src/net/http/server.go:2482
github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/trace.init.0()
        /Users/xxx/Code/go/pkg/mod/github.com/coreos/etcd@v2.3.8+incompatible/Godeps/_workspace/src/golang.org/x/net/trace/trace.go:110 +0x5f

go.mod:
go 1.15

require (
	github.com/coreos/etcd v2.3.8+incompatible
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/go-kratos/etcd v0.0.0-20210301140822-7e78fb4ee5a6
	github.com/go-kratos/kratos/v2 v2.0.0-alpha6
	github.com/golang/protobuf v1.4.3
	github.com/google/uuid v1.2.0 // indirect
	github.com/google/wire v0.5.0
	github.com/gorilla/mux v1.8.0
	github.com/imdario/mergo v0.3.11 // indirect
	github.com/kr/text v0.2.0 // indirect
	github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e // indirect
	go.etcd.io/etcd v2.3.8+incompatible
	golang.org/x/net v0.0.0-20210226172049-e18ecbb05110 // indirect
	golang.org/x/sync v0.0.0-20210220032951-036812b2e83c // indirect
	golang.org/x/sys v0.0.0-20210309040221-94ec62e08169 // indirect
	golang.org/x/text v0.3.5 // indirect
	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
	google.golang.org/genproto v0.0.0-20210303154014-9728d6b83eeb
	google.golang.org/grpc v1.36.0
	google.golang.org/protobuf v1.25.0
	gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f // indirect
	gopkg.in/yaml.v2 v2.4.0
)

**Comment by tonybase** [comment]
最新版本试下？
